USE [DESAFIO]
GO
/****** Object:  Table [dbo].[Convidados]    Script Date: 26/04/2020 18:37:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Convidados](
	[ID] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
	[ID_FUNCIONARIO] [numeric](18, 0) NULL,
	[NOME_CONVIDADO] [varchar](100) NULL,
	[CONSOME_BEBIDAS] [varchar](1) NULL,
	[CANCELADO] [varchar](1) NULL,
	[DATA_CAD] [datetime] NULL,
 CONSTRAINT [PK_CONVIDADOS_CHURRASCO_1] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Funcionarios]    Script Date: 26/04/2020 18:37:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Funcionarios](
	[ID] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
	[FUNCIONARIO] [varchar](100) NULL,
	[CONSOME_BEBIDA] [varchar](1) NULL,
	[CANCELADO] [varchar](1) NULL,
	[DATA_CAD] [datetime] NULL,
 CONSTRAINT [PK_FUNCIONARIOS_CHURRASCO] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Gastos]    Script Date: 26/04/2020 18:37:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Gastos](
	[ID] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
	[GASTO_COMIDA] [numeric](18, 2) NULL,
	[GASTO_BEBIDA] [numeric](18, 2) NULL,
	[DATA_CAD] [datetime] NULL,
 CONSTRAINT [PK_GASTOS_CHURRASCO] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[Convidados] ON 
GO
INSERT [dbo].[Convidados] ([ID], [ID_FUNCIONARIO], [NOME_CONVIDADO], [CONSOME_BEBIDAS], [CANCELADO], [DATA_CAD]) VALUES (CAST(1 AS Numeric(18, 0)), CAST(1 AS Numeric(18, 0)), N'JULIA', N'S', N'N', CAST(N'2020-04-25T18:11:45.040' AS DateTime))
GO
INSERT [dbo].[Convidados] ([ID], [ID_FUNCIONARIO], [NOME_CONVIDADO], [CONSOME_BEBIDAS], [CANCELADO], [DATA_CAD]) VALUES (CAST(2 AS Numeric(18, 0)), CAST(3 AS Numeric(18, 0)), N'VERA', N'S', N'N', CAST(N'2020-04-25T18:15:01.750' AS DateTime))
GO
INSERT [dbo].[Convidados] ([ID], [ID_FUNCIONARIO], [NOME_CONVIDADO], [CONSOME_BEBIDAS], [CANCELADO], [DATA_CAD]) VALUES (CAST(3 AS Numeric(18, 0)), CAST(4 AS Numeric(18, 0)), N'JULIA', N'S', N'N', CAST(N'2020-04-25T20:15:58.767' AS DateTime))
GO
INSERT [dbo].[Convidados] ([ID], [ID_FUNCIONARIO], [NOME_CONVIDADO], [CONSOME_BEBIDAS], [CANCELADO], [DATA_CAD]) VALUES (CAST(6 AS Numeric(18, 0)), CAST(5 AS Numeric(18, 0)), N'RENATO', N'S', N'S', CAST(N'2020-04-26T18:06:38.253' AS DateTime))
GO
SET IDENTITY_INSERT [dbo].[Convidados] OFF
GO
SET IDENTITY_INSERT [dbo].[Funcionarios] ON 
GO
INSERT [dbo].[Funcionarios] ([ID], [FUNCIONARIO], [CONSOME_BEBIDA], [CANCELADO], [DATA_CAD]) VALUES (CAST(1 AS Numeric(18, 0)), N'CARLOS', N'N', N'N', CAST(N'2020-04-25T16:39:14.473' AS DateTime))
GO
INSERT [dbo].[Funcionarios] ([ID], [FUNCIONARIO], [CONSOME_BEBIDA], [CANCELADO], [DATA_CAD]) VALUES (CAST(2 AS Numeric(18, 0)), N'JOSE', N'S', N'N', CAST(N'2020-04-25T16:39:47.690' AS DateTime))
GO
INSERT [dbo].[Funcionarios] ([ID], [FUNCIONARIO], [CONSOME_BEBIDA], [CANCELADO], [DATA_CAD]) VALUES (CAST(3 AS Numeric(18, 0)), N'LUIS', N'S', N'N', CAST(N'2020-04-25T17:27:47.460' AS DateTime))
GO
INSERT [dbo].[Funcionarios] ([ID], [FUNCIONARIO], [CONSOME_BEBIDA], [CANCELADO], [DATA_CAD]) VALUES (CAST(4 AS Numeric(18, 0)), N'RONAN', N'S', N'N', CAST(N'2020-04-25T17:28:07.923' AS DateTime))
GO
INSERT [dbo].[Funcionarios] ([ID], [FUNCIONARIO], [CONSOME_BEBIDA], [CANCELADO], [DATA_CAD]) VALUES (CAST(5 AS Numeric(18, 0)), N'ANA', N'N', N'S', CAST(N'2020-04-25T17:28:26.990' AS DateTime))
GO
INSERT [dbo].[Funcionarios] ([ID], [FUNCIONARIO], [CONSOME_BEBIDA], [CANCELADO], [DATA_CAD]) VALUES (CAST(6 AS Numeric(18, 0)), N'MARCIO', N'N', N'N', CAST(N'2020-04-26T17:55:43.800' AS DateTime))
GO
SET IDENTITY_INSERT [dbo].[Funcionarios] OFF
GO
SET IDENTITY_INSERT [dbo].[Gastos] ON 
GO
INSERT [dbo].[Gastos] ([ID], [GASTO_COMIDA], [GASTO_BEBIDA], [DATA_CAD]) VALUES (CAST(1 AS Numeric(18, 0)), CAST(180.00 AS Numeric(18, 2)), CAST(0.00 AS Numeric(18, 2)), CAST(N'2020-04-26T09:51:26.293' AS DateTime))
GO
INSERT [dbo].[Gastos] ([ID], [GASTO_COMIDA], [GASTO_BEBIDA], [DATA_CAD]) VALUES (CAST(2 AS Numeric(18, 0)), CAST(0.00 AS Numeric(18, 2)), CAST(200.00 AS Numeric(18, 2)), CAST(N'2020-04-26T09:51:31.683' AS DateTime))
GO
SET IDENTITY_INSERT [dbo].[Gastos] OFF
GO
ALTER TABLE [dbo].[Convidados] ADD  CONSTRAINT [DF_CONVIDADOS_CHURRASCO_CONSOME_BEBIDAS]  DEFAULT ('S') FOR [CONSOME_BEBIDAS]
GO
ALTER TABLE [dbo].[Convidados] ADD  CONSTRAINT [DF_CONVIDADOS_CHURRASCO_CANCELADO]  DEFAULT ('N') FOR [CANCELADO]
GO
ALTER TABLE [dbo].[Convidados] ADD  CONSTRAINT [DF_CONVIDADOS_CHURRASCO_DATA_CAD]  DEFAULT (getdate()) FOR [DATA_CAD]
GO
ALTER TABLE [dbo].[Funcionarios] ADD  CONSTRAINT [DF_Table_1_CONVIDADO]  DEFAULT ('S') FOR [CONSOME_BEBIDA]
GO
ALTER TABLE [dbo].[Funcionarios] ADD  CONSTRAINT [DF_FUNCIONARIOS_CHURRASCO_CANCELADO]  DEFAULT ('N') FOR [CANCELADO]
GO
ALTER TABLE [dbo].[Funcionarios] ADD  CONSTRAINT [DF_FUNCIONARIOS_CHURRASCO_DATA_CAD]  DEFAULT (getdate()) FOR [DATA_CAD]
GO
ALTER TABLE [dbo].[Gastos] ADD  CONSTRAINT [DF_GASTOS_CHURRASCO_DATA_CAD]  DEFAULT (getdate()) FOR [DATA_CAD]
GO
